### ISSUE TITLE
Location of go to definition symbols is off

### ISSUE THREAD

**Issue by Gert-dev** [LaurentTreguier/ide-dlang#3]
It seems that when I hold the control key for "go to definition", it behaves strangely and the locations that are being underlined are off. For example, in code such as `this.installAppMenu()`, I can control-click `this` just fine, but hovering over `installAppMenu` underlines the `is.` before it and clicking it has no effect.

Strangely enough, in some rare cases I can get it to work just fine, i.e. `installAppMenu` will be underlined and jumping works, but it usually doesn't. This seems to happen with all member calls I encounter.

What's even more strange is that tooltips display the correct information and hovering over the method call with control _does_ show the method signature as well, so it _is_ recognized, it's just underlining the wrong code ;-).

I'm using [grestful](https://gitlab.com/Gert-dev/grestful) for testing and can reproduce this on [this line](https://gitlab.com/Gert-dev/grestful/blob/master/Application/Class.d#L188).

I'm not sure if this is a problem in this package, dls, or any of its dependencies. If it is not a bug here, I'd be happy to report it somewhere else.

Thanks!

**Comment by LaurentTreguier** [comment]
I can reproduce it in Atom as well, but this is working perfectly fine in VSCode. I'm thinking this might be a bug from `atom-languageclient` or `atom-ide-ui`.
I'll look into it a bit more to be sure though.

**Comment by LaurentTreguier** [comment]
As it turns out, Atom thinks editor lines are 1-based, while VSCode thinks editor lines are 0-based... [This is not the only such case](https://github.com/Microsoft/language-server-protocol/issues/473).

**Comment by LaurentTreguier** [comment]
I'm not sure what is happening here. I'm usually testing with `dub` to test stuff on a real project instead of a hello world, and everything is working in that project, while it's not working in yours. Something weird is definitely going on.

**Comment by LaurentTreguier** [comment]
Ah, I finally found the true culprit : your files had an UTF BOM. I'll push a new DLS version that will fix this.

**Comment by Gert-dev** [comment]
Just gave it a whirl and that indeed fixes it, thanks!

No idea how the BOM came into those files, it's been a while since I worked on it.

**Comment by LaurentTreguier** [comment]
Glad it's fixed !
Strange things happen sometimes.
