### ISSUE TITLE
Work only highlighting

### ISSUE THREAD

**Issue by sr-tream** [LaurentTreguier/ide-dlang#5]
TL;DR:
* Compile dls
* Install ide-dlang
* Setup path to dls in ide-dlang

Result: work only highlighting.

Autocompletion, dscanner, etc doesn't work. Process dls not started.

I tried copy dls binary to PATH and clear edit area with path to dls in ide-dlang settings, but it wouldn't work

**Comment by LaurentTreguier** [comment]
DLS is supposed to be installed automatically by ide-dlang, you shouldn't have to compile it.
What is your OS, which compiler do you use, and do you have any error message ?

**Comment by sr-tream** [comment]
OS: ArchLinux

No error messages.

**Comment by LaurentTreguier** [comment]
https://github.com/d-language-server/dls/issues/14 is also about DLS not working on Arch.
I'll try to setup a minimal VM to try to reproduce the problem.
Which desktop environment are you using?
Do you have libcurl installed?
There is a `ide-dlang.init.logFile` option. If you use it, maybe you could have some error message.

**Comment by sr-tream** [comment]
> Which desktop environment are you using?

KDE

> Do you have libcurl installed?

yes

![libcurl](https://dl.prime-hack.net/127301543222252.png)

> There is a ide-dlang.init.logFile option

It set to '/home/sr_team/dls.log', but file dls.log is empty

**Comment by LaurentTreguier** [comment]
I just realized there was a glaring bug that made the extension error on start... It's fixed in v1.13.2.

Do you have the `atom-ide-ui` Atom package installed ? It's supposed to be installed as a dependency by Atom, but when I installed `ide-dlang` on my VM it did not install it.

**Comment by sr-tream** [comment]
> Do you have the atom-ide-ui Atom package installed ?

No. After installation all work is fine!
