### ISSUE TITLE
Uncaught TypeError: "file" argument must be a non-empty string

### ISSUE THREAD

**Issue by r4j4h** [LaurentTreguier/ide-dlang#6]
1. Installed Atom and a few plugins like ide-dlang and ide-css
2. Opened a project with D files and opened a .d file
3. Saw "Installing DLS"
4. Saw error appear and then notice to install "busy-signal"
5. Waited a while after it successfully installed at "Installing DLS"
6. Closed Atom
7. Re-opened Atom
8. Re-opened .d file
9. Saw "Installing DLS"
10. Saw error appear again

**Atom**: 1.33.1 x64
**Electron**: 2.0.16
**OS**: Microsoft Windows 8.1 Pro
**Thrown From**: [ide-dlang](https://github.com/d-language-server/atom-ide-dlang) package 1.14.1

### Stack Trace

Uncaught TypeError: "file" argument must be a non-empty string

```
At child_process.js:395

TypeError: "file" argument must be a non-empty string
    at normalizeSpawnArguments (child_process.js:395:11)
    at Object.exports.spawn (child_process.js:508:38)
    at Server.server.listen (/packages/ide-dlang/lib/ide-dlang.js:146:26)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:106:13)
    at Server.emit (events.js:208:7)
    at emitListeningNT (net.js:1378:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

### Commands

```
λ dmd -v
DMD32 D Compiler v2.074.1
```

### Non-Core Packages

```
atom-ide-ui 0.13.0 
build 0.70.0 
busy-signal 1.4.3 
ide-css 0.3.2 
ide-dlang 1.14.1 
ide-go 0.12.3 
ide-html 0.5.0 
ide-json 0.2.1 
ide-php 0.7.17 
ide-yaml 0.4.4 
```

**Comment by r4j4h** [comment]
I ran `dub convert -f json` on this project's `dub.sdl` and then it seemed to load up fine. I tried converting back to sdl but it still "worked" but was then installed so not sure if that really had anything to do with it, but figured I'd report it. Also that I got past it. :)

**Comment by LaurentTreguier** [comment]
I would have thought it was a compatibility problem (DMD 2.074 dates from before I even started developing DLS), but if it started working afterwards then maybe it's something else.
I'll look into it when I get back on my machine

**Comment by LaurentTreguier** [comment]
The next DLS version, `v0.21.0`, will have an installer compilable with DMD's dating back to `2.067`; this should fix the issue

**Comment by r4j4h** [comment]
Thanks for looking into it for me :) Sounds like we can close this issue now. :+1:
