### ISSUE TITLE
Removes line breaks before the cursor, messes up the code while typing

### ISSUE THREAD

**Issue by tirithen** [LaurentTreguier/ide-dlang#8]
ide-lang looks like a nice package, the only thing is that it keeps messing up the line breaks while I'm writing my code. Could it maybe be set to only format on file save? I cannot find such an option. Or be smart enough to not format linebreaks right before the cursor?

![removing-trailing-linebreaks-while-coding](https://user-images.githubusercontent.com/245811/64375284-db1d2b00-d025-11e9-8cad-1b955caad187.gif)

**Comment by LaurentTreguier** [comment]
Formatting isn't supposed to happen randomly like this, it should only be triggered by typing a semicolon, saving the file or manually invoking the format command.
I'll look into this.

**Comment by LaurentTreguier** [comment]
It seems to be a problem with atom-ide-ui (which isn't maintained anymore).
I've done two things:
- disabling on-type-formatting by default, to avoid the problem
- removed the direct dependency on atom-ide-ui, so other UI frontends can be tested as well (I saw https://atom-ide-community.github.io the other day for example)
